// examples/nextjs-app-router/app/page.tsx
"use client";
import { useEffect, useState } from "react";
type Content = {
  id: string;
  title: string;
  body: string;
  locale: string;
  status: "draft" | "published";
  createdAt: string;
};
async function call<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(await res.text());
  return res.json();
}
export default function Home() {
  const [items, setItems] = useState<Content[]>([]);
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [locale, setLocale] = useState("en-US");
  const [error, setError] = useState("");
  const refresh = async () => {
    try {
      setItems(await call("/api/octavia/content"));
    } catch (e) {
      setError((e as Error).message);
    }
  };
  useEffect(() => {
    void refresh();
  }, []);
  const create = async () => {
    if (!title || !body || !locale) {
      setError("All fields are required.");
      return;
    }
    await call("/api/octavia/content", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, body, locale }),
    });
    setTitle("");
    setBody("");
    await refresh();
  };
  const publish = async (id: string) => {
    await call(`/api/octavia/content/${id}/publish`, { method: "POST" });
    await refresh();
  };
  return (
    <main
      style={{ fontFamily: "sans-serif", maxWidth: 820, margin: "2rem auto" }}
    >
      <h1>Octavia AI CMS — Next.js</h1>
      {error && <p style={{ color: "crimson" }}>{error}</p>}
      <input
        placeholder="Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <br />
      <textarea
        placeholder="Body"
        value={body}
        onChange={(e) => setBody(e.target.value)}
      />
      <br />
      <input value={locale} onChange={(e) => setLocale(e.target.value)} />
      <br />
      <button onClick={() => void create()}>Create</button>{" "}
      <button onClick={() => void refresh()}>Refresh</button>
      <ul>
        {items.map((i) => (
          <li key={i.id}>
            {i.title} ({i.status}){" "}
            <button
              disabled={i.status === "published"}
              onClick={() => void publish(i.id)}
            >
              Publish
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}

// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { octaviaClient, type Content } from './lib/octaviaClient';
const title=ref(''); const body=ref(''); const locale=ref('en-US'); const items=ref<Content[]>([]); const error=ref('');
const refresh = async()=>{ try{ items.value=await octaviaClient.list(); }catch(e){ error.value=(e as Error).message; } };
const create = async()=>{ if(!title.value || !body.value || !locale.value){ error.value='All fields are required.'; return; } await octaviaClient.create({ title:title.value, body:body.value, locale:locale.value }); title.value=''; body.value=''; await refresh(); };
const publish = async(id:string)=>{ await octaviaClient.publish(id); await refresh(); };
onMounted(()=>{ void refresh(); });
</script>
<template><main style="font-family:sans-serif;max-width:820px;margin:2rem auto"><h1>Octavia AI CMS — Vue Vite</h1><p style="color:crimson">{{ error }}</p><input v-model="title" placeholder="Title" /><br /><textarea v-model="body" placeholder="Body"></textarea><br /><input v-model="locale" /><br /><button @click="create">Create</button> <button @click="refresh">Refresh</button><ul><li v-for="item in items" :key="item.id">{{ item.title }} ({{ item.status }}) <button :disabled="item.status==='published'" @click="publish(item.id)">Publish</button></li></ul></main></template>
